development:
  access_key_id: ENV['AWS_ACCESS_KEY']
  secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
  bucket: picturebrightimages
  
staging:
  access_key_id: ENV['AWS_ACCESS_KEY']
  secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
  bucket: picturebrightimages
  
production:
  access_key_id: ENV['AWS_ACCESS_KEY']
  secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
  bucket: picturebrightimages